import * as dotenv from 'dotenv';
import dotenvParseVariables from 'dotenv-parse-variables';
import { CardRange, CardRarity, DiceCategory, Emotion } from './types';

const rawEnv = dotenv.config();
if (rawEnv.error || rawEnv.parsed === undefined) {
    throw new Error(`Environment variable parsing error: ${rawEnv.error}`);
}

export const env = dotenvParseVariables(rawEnv.parsed) as NodeJS.ProcessEnv;
export const POSTGRES_CONNECTION = {
    database: env.PGDATABASE,
    user: env.PGUSER,
    password: env.PGPASSWORD,
    host: env.PGHOST,
    port: env.PGPORT,
};

export const ALLOWED_CHANNEL_IDS = ['770488167719501867', '936394221940772864', '713993861197987840'];

export const ASSETS_PATH = 'assets';
export const COMMANDS_PATH = './commands';
export const EVENTS_PATH = './events';
export const DOWNLOADED_AUDIO_PATH = 'downloads/audio';

export const DICE_TYPE_EMOJI_MAP: Record<string, string> = {
    DefEvasion: '🔄',
    DefGuard: '🛡️',
    AtkSlash: '🔪',
    AtkPenetrate: '📌',
    AtkHit: '💥',
    StandbyEvasion: '🔄',
    StandbyGuard: '🛡️',
    StandbySlash: '🔪',
    StandbyPenetrate: '📌',
    StandbyHit: '💥',
};
export const DICE_TYPE_CUSTOM_EMOJI_MAP: Record<string, string> = {
    DefEvasion: '<:defensiveevade:940003206648438824>',
    DefGuard: '<:defensiveguard:940003206094782514>',
    AtkSlash: '<:offensiveslash:940003206031872021>',
    AtkPenetrate: '<:offensivepierce:940003206270976010>',
    AtkHit: '<:offensiveblunt:940003205826367519>',
    StandbyEvasion: '<:counterevade:940003205654401067>',
    StandbyGuard: '<:counterguard:940003205750870059>',
    StandbySlash: '<:counterslash:939986712833196112>',
    StandbyPenetrate: '<:counterpierce:940003206241599518>',
    StandbyHit: '<:counterslash:940003205910249594>',
};
export const UNICODE_ASCII_MAP: Record<number, string> = {
    192: 'A',
    201: 'E',
    224: 'a',
    225: 'a',
    232: 'e',
    235: 'e',
    236: 'i',
    237: 'i',
    242: 'o',
    244: 'o',
    250: 'u',
    257: 'a',
    283: 'e',
    299: 'i',
    363: 'u',
    65039: '',
    7929: 'y',
    8217: "'",
    8230: '...',
    8544: 'I',
    8545: 'II',
    8546: 'III',
    8547: 'IV',
};

// MAPPINGS
// General
export const CARD_RARITY_COLOR_MAP: Record<CardRarity, string> = {
    [CardRarity.Common]: '#A8F29F',
    [CardRarity.Uncommon]: '#9AC6FA',
    [CardRarity.Rare]: '#BA97FF',
    [CardRarity.Unique]: '#FFC075',
};
export const DICE_CATEGORY_COLOR_MAP: Record<DiceCategory, string> = {
    [DiceCategory.Def]: '#11b6f7',
    [DiceCategory.Atk]: '#f5481c',
    [DiceCategory.Standby]: '#f9ba12',
};
export const EMOTION_COLOR_MAP: Record<Emotion, string> = {
    [Emotion.Positive]: '#50FF82',
    [Emotion.Negative]: '#FF4141',
};

// Tiphereth
export const TIPHERETH_CARD_RANGE_RAW_DATA_MAP: Record<string, CardRange> = {
    Melee: CardRange.Near,
    Ranged: CardRange.Far,
    'Mass (individual)': CardRange.FarAreaEach,
    'Mass (summation)': CardRange.FarArea,
    Immediate: CardRange.Instance,
};
export const TIPHERETH_CARD_RANGE_CUSTOM_EMOJI_MAP: Record<string, string> = {
    Melee: '<:rangemelee:940003205922824245>',
    Ranged: '<:rangeranged:940003206384209960>',
    'Mass (individual)': '<:rangemass:940003206371618836>',
    'Mass (summation)': '<:rangemass:940003206371618836>',
    Immediate: '<:rangeinstant:940003206166093855>',
};
export const TIPHERETH_CARD_RANGE_IMAGE_MAP: Record<string, string> = {
    Melee: 'range-melee.png',
    Ranged: 'range-ranged.png',
    'Mass (individual)': 'range-mass.png',
    'Mass (summation)': 'range-mass.png',
    Immediate: 'range-instant.png',
};

// Raw data / XML
export const CARD_RANGE_IMAGE_MAP: Record<CardRange, string> = {
    [CardRange.Near]: 'range-melee.png',
    [CardRange.Far]: 'range-ranged.png',
    [CardRange.FarArea]: 'range-mass.png',
    [CardRange.FarAreaEach]: 'range-mass.png',
    [CardRange.Instance]: 'range-instant.png',
};

export const DICE_IMAGE_MAP: Record<string, string> = {
    DefEvasion: 'defensive-evade.png',
    DefGuard: 'defensive-guard.png',
    AtkSlash: 'offensive-slash.png',
    AtkPenetrate: 'offensive-pierce.png',
    AtkHit: 'offensive-blunt.png',
    StandbyEvasion: 'counter-evade.png',
    StandbyGuard: 'counter-guard.png',
    StandbySlash: 'counter-slash.png',
    StandbyPenetrate: 'counter-pierce.png',
    StandbyHit: 'counter-blunt.png',
};

// Discord
export const MAX_ACTION_ROWS = 5;
export const MAX_BUTTONS_PER_ROW = 5;
export const MAX_STATUS_CHARS = 128;

// Fun
export const NAME_POOL = [
    'Acacia',
    'Adam',
    'Alex',
    'Alisa',
    'Anastasia',
    'Angel',
    'Angelina',
    'Anthony',
    'Anton',
    'Ara',
    'Arang',
    'Archer',
    'Asera',
    'Ashely',
    'Aurora',
    'Basil',
    'Bella',
    'Bong - Bong',
    'Brook',
    'Brown',
    'Camille',
    'Cedric',
    'Charlotte',
    'Christoper',
    'Cloie',
    'Cooper',
    'Corbinian',
    'Courtney',
    'Dakota',
    'Dana',
    'Daniel',
    'Daphne',
    'Delaney',
    'Delilah',
    'Destiny',
    'Devona',
    'Dexter',
    'Dia',
    'Diva',
    'Eden',
    'Elena',
    'Elisa',
    'Emilia',
    'Emma',
    'Eugene',
    'Eva',
    'Evangeline',
    'Everett',
    'Evgeni',
    'Finn',
    'Firenze',
    'Frank',
    'Gabriella',
    'Galina',
    'Geminiano',
    'Genie',
    'Georgia',
    'Gonzales',
    'Gregory',
    'Griffin',
    'Gustafsson',
    'HaLynn',
    'Hana',
    'Hannah',
    'Hao',
    'Harry',
    'Haru',
    'Hoon',
    'Hunter',
    'Igoree',
    'Isabel',
    'Jacob',
    'Jake',
    'Joel',
    'Jose',
    'John',
    'Johnson',
    'Joshua',
    'Joy',
    'Julian',
    'Juliet',
    'Justin',
    'Katya',
    'Khanna',
    'Kinsley',
    'Knox',
    'Lamarcus',
    'LaVerne',
    'Loki',
    'London',
    'Louis',
    'Mabel',
    'Maki',
    'Mao',
    'Marinel',
    'Maritza',
    'Mary',
    'Mason',
    'Mason',
    'Max',
    'Maxim',
    'Maximin',
    'Maxwell',
    'Mckenna',
    'Mei',
    'Melendez',
    'Micaela',
    'Miho',
    'Mika',
    'Mirabelle',
    'Morty',
    'Narae',
    'Neville',
    'Nicolas',
    'Nicole',
    'Noah',
    'Odelie',
    'Olive',
    'Oliver',
    'Onorio',
    'Orga',
    'Owen',
    'Pansy',
    'Parker',
    'Paul',
    'Paulinus',
    'Piper',
    'Poussey',
    'Quinn',
    'Ramirez',
    'Ray',
    'Reinhardt',
    'Ria',
    'Rino',
    'River',
    'Robertus',
    'Rogun',
    'Rose',
    'Ruby',
    'Ryn',
    'Samuel',
    'Sanchez',
    'Sergey',
    'Shao',
    'Summer',
    'Susan',
    'Tasha',
    'Tatyana',
    'Tiffany',
    'Tim',
    'Tom',
    'Velasquez',
    'Vera',
    'Viktor',
    'Vincent',
    'Wetherby',
    'Xavier',
    'Yoon - hoo',
    'Yui',
    'Yumi',
    'Yum - yum',
    'Yuri',
];
const ALL_AROUND_HELPER_MESSAGES = [
    'All-Around Helper is well versed in all manner of cleaning. It was designed to take care of a family household all on its own.',
    'When it was discovered that All-Around Helper contained a critical error, it had already been sent to a household.',
    'Blood covered the whole floor, screams echoed, people were running away, and All-Around Helper was gleefully learning the concept of “cleaning”.',
    'A pristine white surface sleek with fine lines and short but efficient legs, All-Around Helper was created to help people.',
    'XX Incorporated, the manufacturer of All-Around Helper, was famous for its robotics products.',
    'All-Around Helper has various functions installed in its body. From burglar alarms and a monitoring system to a coffee maker and light control, it contains everything a household needs.',
    'You may be surprised to learn the numerous functionalities All-Around Helper contains in its compact body. If you were to dismantle it, you would be even more impressed by how efficiently they packed all the necessary equipment into it.',
    'If All-Around Helper were to have any capacity of emotion, it would likely feel very proud of itself for all the help it provides to others.',
    'All-Around Helper always ponders on how it can do more to help.',
    'Most people are unaware of this, but All-Around Helper makes amazing coffee. Of course, no one is likely to ask it to do such a thing now.',
    'The helper-bot can help you with any household chores!',
    'What kind of task do you want me to do? I can help with anything.',
    'Contamination scan complete. Initiating cleaning protocol.',
    'Beebeebeep~ Beep. Contamination spotted! Proceeding with trash disposal protocol.',
    'I will help you with my wide selection of tools.',
    'All-Around Helper spins around NAME, however, <name> continues to concentrate on the task at hand.',
    '<name> has decided against buying a robot vacuum cleaner after seeing All-Around Helper.',
    '<name> only hopes that All-Around Helper’s “cleaning” mode is never activated.',
];
const WHITENIGHT_MESSAGES = [
    '<name>, repented, enters the Containment Unit, following His divine light.',
    'What maketh thee hesitate? I work miracles here.',
    'WhiteNight looks like a fetus, but it seems as though He needs no nannying.',
    'When the bell struck twelve, the facility was swallowed by a blinding light. It was the light of redemption for His disciples.',
    'Only silence fills the air around WhiteNight.',
    'WhiteNight absorbs all light and sound which surrounds Him.',
    'WhiteNight came here to redeem you and lead the new world.',
    'WhiteNight arrived from the end of the world, and He walks towards the beginning of the new world.',
    '<name>, why art thou in fear? I shall not leave thee until I have completed my mission.”',
    '<name>, be not frightened. I am thy savior and I shall be with thee.',
    'I heard thy cries. Thy heart reached me. <name>, thou hath called me.',
    'Do not fear, for I am with thee. Thou shalt not leave until I permit thee.',
    'Do not trust time. I shall guide thee.',
    'Do not deny me. Why dost thou doubt me when I am in front of thine eyes?',
    'My story is nowhere, unknown to all.'
];
export const STATUS_MESSAGES = [
    ...ALL_AROUND_HELPER_MESSAGES,
    ...WHITENIGHT_MESSAGES
];
